# 使用 Node.js 18 作为基础镜像
FROM node:18-alpine

# 设置工作目录
WORKDIR /app

# 复制 package.json 和 package-lock.json 到容器中
COPY package*.json ./
COPY prisma ./prisma/

# 安装应用程序依赖
RUN npm install

# 复制应用程序代码到容器中
COPY . .

# 生成 Prisma
RUN npm install -g prisma

# 生成 Prisma 客户端
RUN prisma generate

# 暴露应用程序的端口
EXPOSE 3000
# 暴露 prisma studio 端口
EXPOSE 5555

# 启动应用程序
CMD ["npm", "run", "start:migrate:dev"]
