version: '3'

services:
  express-api:
    container_name: express-api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres-db
    env_file:
      - .env.production # 生产环境
    network_mode: "host"
  postgres-db:
    image: postgres:14
    restart: always
    container_name: postgres-db
    environment:
      - POSTGRES_DB=prod
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123456
    volumes:
      - /home/docker-compose-kit/db-data:/var/lib/postgresql/data
    network_mode: "host"
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    # ports:
    #   - "80:80"
    # - "443:443"
    volumes:
      # - /etc/localtime:/etc/localtime
      - /home/docker-compose-kit/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/docker-compose-kit/nginx/logs:/var/log/nginx
      # - /home/docker-compose-kit/nginx/cert:/etc/nginx/cert
    depends_on:
      - express-api
    network_mode: "host"
