version: '3'

services:
  express-api-dev:
    container_name: express-api-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 4000:3000
      - 6555:5555 # 暴露 prisma 可视化，方便调试
    depends_on:
      - pgsql
    env_file:
      - .env # 开发环境
  postgres-db-dev:
    image: postgres:14
    restart: always
    container_name: postgres-db-dev
    environment:
      - POSTGRES_DB=dev
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123456
    ports:
      - 6432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    name: express-db

# version: '3'

# services:
#   express-api:
#     container_name: express-api
#     build:
#       context: .
#       dockerfile: Dockerfile
#     depends_on:
#       - postgres-db
#     env_file:
#       - .env.production # 生产环境
#     networks:
#       - my-network

#   postgres-db:
#     image: postgres:14
#     restart: always
#     container_name: postgres-db
#     environment:
#       - POSTGRES_DB=prod
#       - POSTGRES_USER=user
#       - POSTGRES_PASSWORD=123456
#     volumes:
#       - /home/docker-compose-kit/db-data:/var/lib/postgresql/data
#     networks:
#       - my-network

#   nginx:
#     image: nginx:stable-alpine
#     container_name: nginx
#     restart: always
#     volumes:
#       - /home/docker-compose-kit/nginx/nginx.conf:/etc/nginx/nginx.conf
#       - /home/docker-compose-kit/nginx/logs:/var/log/nginx
#     depends_on:
#       - express-api
#     networks:
#       - my-network

# networks:
#   my-network:
