version: '3'

services:
  express-api:
    container_name: express-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres-db
    env_file:
      - .env.production # 生产环境
  postgres-db:
    image: postgres:14
    restart: always
    container_name: postgres-db
    environment:
      - POSTGRES_DB=prod
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=123456
    ports:
      - 5432:5432
    volumes:
      - /home/docker-compose-kit/db-data:/var/lib/postgresql/data
